spring.application.name=SpringSecTelusko

spring.security.user.name=kabin
spring.security.user.password=2078

# postgresql
# data source url
spring.datasource.url = jdbc:postgresql://localhost:5432/telusko1
# username
spring.datasource.username = postgres
# password
spring.datasource.password = 2078
# driver class name
spring.datasource.driver-class-name = org.postgresql.Driver